Ex 1
TakedaLab/B4Lecture-2023 pull request #7
Opened 2023-04-28 09:49 UTC by 980055617

# What

課題1のコードができましたのでレビューをお願いします。

例:
- 時間信号からスペクトログラムへの変換及び逆変換の実装及びグラフ表示
- 実行コマンド
 `$ python main.py`

# Result

結果の画像を添付しております。

2023-05-02 04:08 UTC, tkmyamamoto commented
（今後はBotから以下のメッセージが流れる予定です）
@980055617 
課題の提出お疲れ様です！
レビュアーが自動で割り当てられない場合はお知らせください。
また、レビュアーが割り振られていても反応がない場合は気づいていない可能性があるので催促してあげてください。
コーディングは自動でチェックされます．できる範囲で構わないのでエラーメッセージや[こちら](https://github.com/TakedaLab/B4Lecture-2023/blob/master/docs/TIPS.md#github-actionsのciによるコーディングチェック)を参考に修正してみてください。

@kimi-research @tkmyamamoto 
このPRのレビュアーに指名されました。
M1、M2はレビューをして、最後に忘れずapproveをしてください。
B4は感想や参考になった点などなんでも良いのでコメントしてください。

2023-05-02 04:53 UTC, tkmyamamoto commented
とてもよくできていると思います！
実装は問題ないです．気になったところだけコメント残していくので，もし良ければ修正してみてください．

2023-05-02 05:07 UTC, tkmyamamoto requested changes
余裕があれば`black main.py`でlintをかけておくといいと思います．
`comparision_graph_ex1.png`が2つあるようなのでどちらか片方は消しておきましょう．
PRにも画像をはっ付けてもらえると嬉しいです．

2023-05-02 05:07 UTC, tkmyamamoto commented on ex1/t_kawanishi/main.py
> +    freq = freq / 1000
kHz -> Hzの変換をしているかと思いますが，もし音源が声などであればそのままHzのほうがスペクトログラムは見やすいかもしれません．人の声の音域は〜1000Hz程度と聞いた記憶があります（音のことは詳しくないので間違っているかもしれません...）

2023-05-02 05:07 UTC, tkmyamamoto commented on ex1/t_kawanishi/main.py
> +data, samplerate = load_sound(SOUND_PATH)
ここから最後までは`if __name__ == '__main__'`に入れて書くのが良いと思います．
https://note.nkmk.me/python-if-name-main/

2023-05-02 05:48 UTC, 980055617 commented on ex1/t_kawanishi/main.py
> +data, samplerate = load_sound(SOUND_PATH)
コメントありがとうございます。
今から変更します。

2023-05-02 05:50 UTC, 980055617 commented on ex1/t_kawanishi/main.py
> +    freq = freq / 1000
コメントありがとうございます。
kHzのほうが数字の値が小さくて見やすいかなって思ったんですけど、
確かに人の音域は〜1000Hzなので、元のままのほうが見やすいと思いますので、変更します。

2023-05-02 06:04 UTC, 980055617 commented on ex1/t_kawanishi/main.py
> +    """Load sound file."""
コメントありがとうございます。
コーディングにおいて引数や返り値の説明に関するおすすめの参考がございましたら教えていただきたいです。

2023-05-02 06:06 UTC, 980055617 commented on ex1/t_kawanishi/main.py
> +overlap_r = 0.9                              # overlap rate between 0 to 1
コメントありがとうございます。
つけようかどうか迷ってたんですけど、どうせ音源一個しか使わないと思ってやめましたが、
今後再利用することを考えるとつけたほうが使いやすいので、つけます！

2023-05-02 08:01 UTC, 980055617 commented
変更ができましたので、チェックお願いします。

2023-05-02 10:24 UTC, tkmyamamoto commented on ex1/t_kawanishi/main.py
> +overlap_r = 0.9                              # overlap rate between 0 to 1
なるほど，そうだったんですね
このへんは好みなのでお任せします！

2023-05-02 10:26 UTC, tkmyamamoto commented on ex1/t_kawanishi/main.py
> +    """Load sound file."""
これオススメです
https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

2023-05-02 10:32 UTC, tkmyamamoto commented on ex1/t_kawanishi/main.py
> +    freq = freq / 1000
図の単位も直しておきましょう．
課題の発表資料づくりのときに，0-1000Hzあたりで周波数軸を拡大してみて音源と合わせて考察してみるといいかもしれませんね！

2023-05-02 10:36 UTC, tkmyamamoto commented
CIも通っていて素晴らしいです．とてもいい感じだと思います．
一つだけ，逆変換後の波形の振幅が最初に比べて大きくなっている（5倍くらい）のが気になったので是非修正してみてください．
最後に，その逆変換による時間信号を実際に聴いてみるのも面白いと思います．

2023-05-02 11:24 UTC, 980055617 commented on ex1/t_kawanishi/main.py
> +    freq = freq / 1000
修正しときました。
考察の参考になります！ありがとうございます！

2023-05-02 11:25 UTC, 980055617 commented
> CIも通っていて素晴らしいです．とてもいい感じだと思います． 一つだけ，逆変換後の波形の振幅が最初に比べて大きくなっている（5倍くらい）のが気になったので是非修正してみてください． 最後に，その逆変換による時間信号を実際に聴いてみるのも面白いと思います．

修正しました！
逆変換の時の挙動を改めて見直して、よくないところに気づきました！
ありがとうございます。

2023-05-02 11:35 UTC, 980055617 commented
いただいたコメントをもとに関数を修正しました。
また、考察をするために逆変換で戻した音声を出力し、聞けるようにしました。

2023-05-03 02:46 UTC, tkmyamamoto requested changes
良いと思います！
[このコミット](https://github.com/TakedaLab/B4Lecture-2023/pull/7/commits/b69689870bfcee24e2ef042b9f7b36c2b7de55a5)だけ取り消してもらえますか？`ex1/figs/result.png`はおそらく課題の図なので，マージされると消えちゃいます．

2023-05-03 06:51 UTC, 980055617 commented
元の状態に戻しました。
宜しくお願い致します。

2023-05-03 06:57 UTC, tkmyamamoto approved these changes
LGTM
お疲れ様でした！次回も頑張ってください

2023-05-10 08:54 UTC, merged